export const EXPIRE_TIME = 60 * 60 * 24 * 29 * 1000; // 29 Days
export const APP_SECRET = process.env.APP_SECRET;
export const BAD_REQUEST = { message: "Bad Request" };
export const SERVER_ERROR = { message: "Internal Server Error" };
export const UNAUTHORIZED = { message: "Unauthorized" };
export const NOT_FOUND = { message: "Not found" };
export const SUCCESS = { message: "Action successful" };
export const COOKIE_KEY = "act";
export const REFRESH_TOKEN_KEY = "rft";
